LPanels = {
	["Default"] = {
		{	name = "TOPInfoPanel",
			anchor_to = "TOPRIGHT",
			width = 146,
			height = 16,
			y_off = -4,
			x_off = -5,
			bg_color = {0.1,0.1,0.1},
			bg_alpha = 0.6,
			strata = "BACKGROUND",
			border = "Interface\\Buttons\\WHITE8x8",
			border_size = "1",
			border_color = {65/255, 74/255, 79/255},
			border_alpha = "0.99"
		},
		{	name = "TOPInfoPanelShadow",
			anchor_to = "TOPRIGHT",
			width = 156,
			height = 26,
			y_off = 1,
			x_off = 0,
			bg_color = {0,0,0},
			bg_alpha = 0,
			border = "glowTex",
			border_size = "5",
			border_color = {0,0,0},
			border_alpha = "0.99"
		},
		
		{	name = "LeftInfoPanel",
			anchor_to = "BOTTOMLEFT",
			width = 330,
			height = 15,
			y_off = 5,
			x_off = 5,
			bg_color = {0.1,0.1,0.1},
			bg_alpha = 0.6,
			strata = "BACKGROUND",
			border = "Interface\\Buttons\\WHITE8x8",
			border_size = "1",
			border_color = {65/255, 74/255, 79/255},
			border_alpha = "0.99"
		},
		{	name = "LeftInfoPanelShadow",
			anchor_to = "BOTTOMLEFT",
			width = 340,
			height = 25,
			y_off = 0,
			x_off = 0,
			bg_color = {0,0,0},
			bg_alpha = 0,
			border = "glowTex",
			border_size = "5",
			border_color = {0,0,0},
			border_alpha = "0.99"
		},
		
		{	name = "BOTTOMInfoPanel",
			anchor_to = "BOTTOM",
			width = 560,
			height = 5,
			y_off = 5,
			x_off = 0,
			bg_color = {0.1,0.1,0.1},
			bg_alpha = 0.6,
			strata = "BACKGROUND",
			border = "Interface\\Buttons\\WHITE8x8",
			border_size = "1",
			border_color = {65/255, 74/255, 79/255},
			border_alpha = "0.99"
		},
		{	name = "BOTTOMInfoPanelShadow",
			anchor_to = "BOTTOM",
			width = 570,
			height = 15,
			y_off = 0,
			x_off = 0,
			bg_color = {0,0,0},
			bg_alpha = 0,
			border = "glowTex",
			border_size = "5",
			border_color = {0,0,0},
			border_alpha = "0.99"
		},
      
		{	name = "RightInfoPanel",
			anchor_to = "BOTTOMRIGHT",
			width = 330,
			height = 15,
			y_off = 5,
			x_off = -5,
			bg_color = {0.1,0.1,0.1},
			bg_alpha = 0.6,
			strata = "BACKGROUND",
			border = "Interface\\Buttons\\WHITE8x8",
			border_size = "1",
			border_color = {65/255, 74/255, 79/255},
			border_alpha = "0.99"
		},
        {	name = "RightInfoPanelShadow",
			anchor_to = "BOTTOMRIGHT",
			width = 340,
			height = 25,
			y_off = 0,
			x_off = 0,
			bg_color = {0,0,0},
			bg_alpha = 0,
			border = "glowTex",
			border_size = "5",
			border_color = {0,0,0},
			border_alpha = "0.99"
		},
		{	name = "Backgroundleft",
			anchor_to = "BOTTOMLEFT",
			width = 330,
			height = 110,
			y_off = 25,
			x_off = 5,
			bg_color = {0.1,0.1,0.1},
			bg_alpha = 0.6,
			strata = "BACKGROUND",
			border = "Interface\\Buttons\\WHITE8x8",
			border_size = "1",
			border_color = {65/255, 74/255, 79/255},
			border_alpha = "0.99"
		},
		{	name = "BackgroundleftShadow",
			anchor_to = "BOTTOMLEFT",
			width = 340,
			height = 120,
			y_off = 20,
			x_off = 0,
			bg_color = {0,0,0},
			bg_alpha = 0,
			border = "glowTex",
			border_size = "5",
			border_color = {0,0,0},
			border_alpha = "0.99"
		},
		{	name = "Backgroundright",
			anchor_to = "BOTTOMRIGHT",
			width = 330,
			height = 110,
			y_off = 25,
			x_off = -5,
			bg_color = {0.1,0.1,0.1},
			bg_alpha = 0.6,
			strata = "BACKGROUND",
			border = "Interface\\Buttons\\WHITE8x8",
			border_size = "1",
			border_color = {65/255, 74/255, 79/255},
			border_alpha = "0.99"
		},
		{	name = "BackgroundrightShadow",
			anchor_to = "BOTTOMRIGHT",
			width = 340,
			height = 120,
			y_off = 20,
			x_off = 0,
			bg_color = {0,0,0},
			bg_alpha = 0,
			border = "glowTex",
			border_size = "5",
			border_color = {0,0,0},
			border_alpha = "0.99"
		},
		{	name = "Minimap",
			anchor_to = "TOPRIGHT",
			width = 146,
			height = 147,
			y_off = -23,
			x_off = -5,
			bg_color = {0.1,0.1,0.1},
			bg_alpha = 0.6,
			strata = "BACKGROUND",
			border = "Interface\\Buttons\\WHITE8x8",
			border_size = "1",
			border_color = {65/255, 74/255, 79/255},
			border_alpha = "0.99"
		},
		{	name = "MinimapShadow",
			anchor_to = "TOPRIGHT",
			width = 156,
			height = 157,
			y_off = -18,
			x_off = -0,
			bg_color = {0,0,0},
			bg_alpha = 0,
			border = "glowTex",
			border_size = "5",
			border_color = {0,0,0},
			border_alpha = "0.99"
		},
	},
}
